### ISSUE TITLE
Rooting Smart Watch

### ISSUE THREAD

**Issue by EtainLove** [EtainClub/etainclub#5]
could you please make a step-by-step video about the rooting process of Zeblaze Blitz smart watch? I would appreciate it since the description is very confusing to me. Thanks! :)﻿

**Comment by EtainLove** [comment]
Please refer to [this article](https://github.com/EtainClub/etainclub/wiki/Smart-Watch).
For you, I wrote down the step-by-step procedure to root the watch.
Enjoy! and contact again if you encounter any problems.

**Comment by aakinci** [comment]
very nice tutorial
i need help about it
when in step 4
i power off your watch and connect the watch to PC using the charger, pc recognises the watch I hear usb attached sound, then i hear detached sound immediately!, and wait for along time but nothing happens
What do i do wrong 
please help me

best regards

**Comment by EtainLove** [comment]
Did you follow all the procedure correctly?
If not, let me know which part you did wrong.
I want my phone to be the same situation as yours.

Have you tried the following?
"Hold power botton for a while, when your phone give balck screen release power botton, your blitz back to charger mode, now you need flash a rom."
