### ISSUE TITLE
여러대 장애물 주행 질문드립니다.

### ISSUE THREAD

**Issue by Cumas** [EtainClub/etainclub#7]
ROS Kinetic 강좌3, 4 잘 보고 따라하였습니다. 
저의 환경은 Indigo에서 실험중입니다. 

4대가 가지보에서 나타나지만 움직이지가 않습니다. 
왜이런지 이유를 잘 모르겠습니다.
저의 실험 소스파은 첨부하였습니다.

[mobile_robot_sim.tar.gz](https://github.com/EtainClub/etainclub/files/780463/mobile_robot_sim.tar.gz)

**Comment by EtainLove** [comment]
@Cumas 
issue를 closed 하셨는데 의도하신건가요?

Indigo의 Gazebo 버전은 2.x 입니다. Kinetic은 7.x 이고요. 차이가 매우 큽니다.
되도록 최신 Gazebo를 사용하길 권합니다.
제 코드도 Kinetic에서 가끔 Gazebo 실행시 에러가 발생하기도 합니다.
아마 Cumas님도 Gazebo 실행화면에 빨갛게 Error Message가 떴을거 같습니다. 확인해 보세요.

**Comment by Cumas** [comment]
@EtainLove 수정하여 자료첨부과정에서 closed로 잘못 누른거 같습니다..
네 노트북 버전 Kinetic로 바꾸고 해보겠습니다.
친절한 답변 너무나 감사합니다.
